export const load = () => ({
  slug: "tool-catalog",
  title: "Tool Reference",
  section: "Users",
  description:
    "Complete reference for all 30 PEN tools — parameters, CDP domains, and output formats.",
  headings: [
    { id: "memory-4-tools", text: "Memory (4 tools)", depth: 2 },
    { id: "pen_heap_snapshot", text: "pen_heap_snapshot", depth: 3 },
    { id: "pen_heap_diff", text: "pen_heap_diff", depth: 3 },
    { id: "pen_heap_track", text: "pen_heap_track", depth: 3 },
    { id: "pen_heap_sampling", text: "pen_heap_sampling", depth: 3 },
    { id: "cpu-3-tools", text: "CPU (3 tools)", depth: 2 },
    { id: "pen_cpu_profile", text: "pen_cpu_profile", depth: 3 },
    { id: "pen_capture_trace", text: "pen_capture_trace", depth: 3 },
    { id: "pen_trace_insights", text: "pen_trace_insights", depth: 3 },
    { id: "network-4-tools", text: "Network (4 tools)", depth: 2 },
    { id: "pen_network_enable", text: "pen_network_enable", depth: 3 },
    { id: "pen_network_waterfall", text: "pen_network_waterfall", depth: 3 },
    { id: "pen_network_request", text: "pen_network_request", depth: 3 },
    { id: "pen_network_blocking", text: "pen_network_blocking", depth: 3 },
    { id: "coverage-2-tools", text: "Coverage (2 tools)", depth: 2 },
    { id: "pen_js_coverage", text: "pen_js_coverage", depth: 3 },
    { id: "pen_css_coverage", text: "pen_css_coverage", depth: 3 },
    { id: "audit-3-tools", text: "Audit (3 tools)", depth: 2 },
    {
      id: "pen_performance_metrics",
      text: "pen_performance_metrics",
      depth: 3,
    },
    { id: "pen_web_vitals", text: "pen_web_vitals", depth: 3 },
    {
      id: "pen_accessibility_check",
      text: "pen_accessibility_check",
      depth: 3,
    },
    { id: "source-3-tools", text: "Source (3 tools)", depth: 2 },
    { id: "pen_list_sources", text: "pen_list_sources", depth: 3 },
    { id: "pen_source_content", text: "pen_source_content", depth: 3 },
    { id: "pen_search_source", text: "pen_search_source", depth: 3 },
    { id: "console-2-tools", text: "Console (2 tools)", depth: 2 },
    { id: "pen_console_enable", text: "pen_console_enable", depth: 3 },
    { id: "pen_console_messages", text: "pen_console_messages", depth: 3 },
    { id: "lighthouse-1-tool", text: "Lighthouse (1 tool)", depth: 2 },
    { id: "pen_lighthouse", text: "pen_lighthouse", depth: 3 },
    { id: "utility-8-tools", text: "Utility (8 tools)", depth: 2 },
    { id: "pen_status", text: "pen_status", depth: 3 },
    { id: "pen_list_pages", text: "pen_list_pages", depth: 3 },
    { id: "pen_select_page", text: "pen_select_page", depth: 3 },
    { id: "pen_navigate", text: "pen_navigate", depth: 3 },
    { id: "pen_collect_garbage", text: "pen_collect_garbage", depth: 3 },
    { id: "pen_screenshot", text: "pen_screenshot", depth: 3 },
    { id: "pen_emulate", text: "pen_emulate", depth: 3 },
    { id: "pen_evaluate", text: "pen_evaluate", depth: 3 },
    { id: "rate-limits", text: "Rate Limits", depth: 2 },
    { id: "tool-chaining", text: "Tool Chaining", depth: 2 },
  ],
});
