<script lang="ts">
  import DocPage from "$lib/content/DocPage.svelte";
  import CodeBlock from "$lib/content/CodeBlock.svelte";
  import Mermaid from "$lib/content/Mermaid.svelte";
  import type { PageProps } from "./$types";

  let { data }: PageProps = $props();
</script>

<DocPage
  title={data.title}
  description={data.description}
  slug={data.slug}
  headings={data.headings}
>
  <h1>Data Streaming</h1>

  <h2 id="the-problem">The Problem</h2>

  <p>Some CDP operations produce serious payloads:</p>

  <div class="table-wrapper">
    <table>
      <thead><tr><th>Operation</th><th>Typical Size</th><th>Worst Case</th></tr></thead>
      <tbody>
        <tr><td>Heap snapshot</td><td>50–500 MB</td><td>2+ GB</td></tr>
        <tr><td>Chrome trace</td><td>5–50 MB</td><td>500+ MB</td></tr>
        <tr><td>CPU profile</td><td>100 KB–5 MB</td><td>20 MB</td></tr>
        <tr><td>Coverage data</td><td>10–500 KB</td><td>5 MB</td></tr>
      </tbody>
    </table>
  </div>

  <p>
    Loading these into memory would crash PEN or eat the host alive. So PEN
    streams everything to temp files.
  </p>

  <h2 id="heap-snapshot-streaming">Heap Snapshot Streaming</h2>

  <p>
    CDP delivers heap snapshots as a stream of
    <code>HeapProfiler.addHeapSnapshotChunk</code> events — each one carries a
    string chunk of JSON.
  </p>

  <Mermaid
    code={`sequenceDiagram
    participant Handler as Tool Handler
    participant Lock as OperationLock
    participant Temp as Temp File (disk)
    participant CDP as Chrome (CDP)
    participant MCP as MCP Client

    Handler->>+Lock: Acquire("HeapProfiler")
    Handler->>Temp: CreateSecureTempFile("heap-")
    Handler->>CDP: HeapProfiler.collectGarbage (optional)
    Handler->>CDP: HeapProfiler.takeHeapSnapshot

    loop Each chunk (constant memory)
        CDP-->>Handler: addHeapSnapshotChunk
        Handler->>Temp: Write chunk to disk
    end

    CDP-->>Handler: reportHeapSnapshotProgress
    Handler--)MCP: Progress notification

    Handler->>Temp: Seek to start, analyze from disk
    Handler-->>MCP: Return structured analysis
    Handler->>-Lock: Release`}
  />

  <p>
    Memory stays flat no matter how big the heap gets — chunks go straight to
    disk.
  </p>

  <h2 id="trace-streaming">Trace Streaming</h2>

  <p>
    Chrome traces use <code>Tracing.start</code> with
    <code>transferMode: "ReturnAsStream"</code> and optional gzip.
  </p>

  <Mermaid
    code={`sequenceDiagram
    participant Handler as Tool Handler
    participant Lock as OperationLock
    participant CDP as Chrome (CDP)
    participant Temp as Temp File (disk)

    Handler->>+Lock: Acquire("Tracing")
    Handler->>CDP: Tracing.start (categories, ReturnAsStream)

    Note over Handler: Wait for capture duration

    Handler->>CDP: Tracing.end
    CDP-->>Handler: tracingComplete (IO.StreamHandle)

    loop Until eof
        Handler->>CDP: IO.read(handle)
        CDP-->>Handler: chunk data
        Handler->>Temp: Write chunk
    end

    Handler->>Handler: Analyze trace file
    Handler->>-Lock: Release`}
  />

  <h3 id="buffer-management">Buffer Management</h3>

  <p>
    Chrome has a finite trace buffer. PEN watches
    <code>Tracing.bufferUsage</code> events during capture. If
    <code>percentFull &gt; 0.9</code>, PEN fires a progress warning. If the
    buffer fills completely, the trace gets truncated and PEN notes it in the
    output.
  </p>

  <h2 id="temp-files">Temp Files</h2>

  <p>All temp files live under <code>os.TempDir()/pen/</code>:</p>

  <ul>
    <li>Created with <code>0600</code> permissions (owner-only read/write)</li>
    <li>Directory created with <code>0700</code> permissions</li>
    <li>Path validated via <code>security.ValidateTempPath</code> before any read/write</li>
    <li>Cleaned up on normal exit via <code>defer cleanupTempDir(logger)</code> in <code>main.go</code></li>
    <li>Cleaned up on context cancellation via <code>defer</code> in each handler</li>
  </ul>

  <p>
    Each temp file has a prefix indicating its type (<code>heap-</code>,
    <code>trace-</code>, etc.) and a unique suffix generated by
    <code>os.CreateTemp</code>.
  </p>

  <h2 id="progress-notifications">Progress Notifications</h2>

  <p>
    Long-running tools send MCP progress notifications so the client knows
    things are moving:
  </p>

  <CodeBlock
    lang="go"
    code="server.NotifyProgress(ctx, req, bytesWritten, totalBytes, &quot;streaming heap snapshot...&quot;)"
  />

  <p>
    Fires only if the client sent a progress token in the request. Safe to call
    every time — a missing token or nil session is a no-op.
  </p>

  <h2 id="data-flow-diagram">Data Flow Diagram</h2>

  <Mermaid
    code={`sequenceDiagram
    participant CDP as CDP Event Stream
    participant PEN
    participant LLM

    CDP->>PEN: addHeapSnapshotChunk (1)
    Note right of PEN: Write to temp file
    CDP->>PEN: addHeapSnapshotChunk (2)
    Note right of PEN: Write to temp file
    CDP->>PEN: addHeapSnapshotChunk (...N)
    Note right of PEN: Write to temp file
    PEN--)LLM: Progress notification
    CDP->>PEN: reportHeapSnapshotProgress
    Note right of PEN: Analyze from disk
    Note right of PEN: Format structured output
    PEN->>LLM: CallToolResult
    Note right of PEN: Delete temp file`}
  />
</DocPage>
